// vue-axes-trade/src/App.vue
<script setup lang="ts">
import { onMounted } from 'vue'
import { useRoute } from 'vue-router'
import NavBar from '@/components/NavBar.vue'
import Footer from '@/components/Footer.vue'

const route = useRoute()

// Fonction pour suivre les visites de pages
onMounted(() => {
  // Tracking de page view pour l'analytics
  trackPageView(route.path)
})

// Enregistrer la vue de page dans l'analytics
const trackPageView = async (path: string) => {
  try {
    await fetch('/api/analytics/page-view', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        path,
        referrer: document.referrer || null,
        userAgent: navigator.userAgent,
      }),
    })
  } catch (error) {
    console.error('Failed to track page view:', error)
  }
}
</script>

<template>
  <div id="app" class="flex flex-col min-h-screen">
    <NavBar />
    <main class="flex-grow">
      <router-view></router-view>
    </main>
    <Footer />
  </div>
</template>

<style>
/* Les styles globaux sont gérés par Tailwind CSS et définis dans le fichier index.css */
</style>

// client/src/App.tsx
import { Route, Switch } from "wouter";
import { queryClient } from "./lib/queryClient";
import { QueryClientProvider } from "@tanstack/react-query";
import { Toaster } from "@/components/ui/toaster";
import NotFound from "@/pages/not-found";
import Home from "@/pages/Home";
import Blog from "@/pages/Blog";
import Products from "@/pages/Products";
import Admin from "@/pages/Admin";
import LiveChat from "@/components/LiveChat";
import { useEffect } from "react";
import { apiRequest } from "@/lib/queryClient";

// Analytics tracking
function PageTracker() {
  useEffect(() => {
    // Track page view
    const trackPageView = async () => {
      try {
        await apiRequest('/api/analytics/pageview', {
          method: 'POST',
          body: JSON.stringify({
            path: window.location.pathname,
            referrer: document.referrer || null,
            userAgent: navigator.userAgent || null
          })
        });
      } catch (error) {
        console.error('Error tracking page view:', error);
      }
    };
    
    trackPageView();
  }, [window.location.pathname]);
  
  return null;
}

function Router() {
  return (
    <>
      <PageTracker />
      <Switch>
        <Route path="/" component={Home} />
        <Route path="/blog/:slug?" component={Blog} />
        <Route path="/products/:slug?" component={Products} />
        <Route path="/admin" component={Admin} />
        <Route component={NotFound} />
      </Switch>
    </>
  );
}

function App() {
  return (
    <QueryClientProvider client={queryClient}>
      <Router />
      <LiveChat />
      <Toaster />
    </QueryClientProvider>
  );
}

export default App;
