// vue-axes-trade/src/components/Features.vue
<script setup lang="ts">
import { library } from '@fortawesome/fontawesome-svg-core'
import { faPrint, faShieldHalved, faGears, faChartLine, faHeadset, faLeaf } from '@fortawesome/free-solid-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Ajouter les icônes à la bibliothèque
library.add(faPrint, faShieldHalved, faGears, faChartLine, faHeadset, faLeaf)

// Liste des fonctionnalités
const features = [
  {
    icon: 'print',
    title: 'Haute qualité d\'impression',
    description: 'Nos imprimantes offrent une qualité d\'impression exceptionnelle pour tous vos besoins professionnels.'
  },
  {
    icon: 'shield-halved',
    title: 'Garantie étendue',
    description: 'Tous nos produits sont couverts par une garantie de 3 ans, pour votre tranquillité d\'esprit.'
  },
  {
    icon: 'gears',
    title: 'Solutions personnalisées',
    description: 'Nous proposons des solutions sur mesure adaptées aux besoins spécifiques de votre entreprise.'
  },
  {
    icon: 'chart-line',
    title: 'Optimisation des coûts',
    description: 'Réduisez vos coûts d\'impression grâce à nos solutions économiques et écologiques.'
  },
  {
    icon: 'headset',
    title: 'Support technique dédié',
    description: 'Notre équipe de support est disponible pour vous assister et répondre à toutes vos questions.'
  },
  {
    icon: 'leaf',
    title: 'Eco-responsable',
    description: 'Nos produits sont conçus dans une démarche écologique, réduisant l\'impact environnemental.'
  }
]
</script>

<template>
  <section class="py-16 bg-white">
    <div class="container mx-auto px-4">
      <div class="text-center mb-12">
        <h2 class="text-3xl md:text-4xl font-bold">Pourquoi choisir AxesTrade ?</h2>
        <p class="text-lg text-gray-600 mt-4 max-w-2xl mx-auto">
          Nous proposons des solutions d'impression professionnelles complètes, adaptées à vos besoins spécifiques.
        </p>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div 
          v-for="(feature, index) in features" 
          :key="index" 
          class="bg-gray-50 p-6 rounded-lg transition-transform hover:scale-105"
        >
          <div class="flex items-start">
            <div class="mr-4 bg-primary text-white p-3 rounded-lg">
              <FontAwesomeIcon :icon="feature.icon" class="text-xl" />
            </div>
            <div>
              <h3 class="text-xl font-bold mb-2">{{ feature.title }}</h3>
              <p class="text-gray-600">{{ feature.description }}</p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

// client/src/components/Features.tsx
import React from "react";

const features = [
  {
    icon: "award",
    title: "Expertise & Qualité",
    description: "Plus de 10 ans d'expérience dans la vente et maintenance d'équipements d'impression."
  },
  {
    icon: "hand-holding-usd",
    title: "Économies Garanties",
    description: "Des solutions optimisées pour réduire vos coûts d'impression et votre consommation d'énergie."
  },
  {
    icon: "tools",
    title: "Service Après-vente",
    description: "Maintenance rapide et efficace avec des techniciens qualifiés pour minimiser les interruptions."
  },
  {
    icon: "leaf",
    title: "Engagement Écologique",
    description: "Solutions éco-responsables et recyclage des consommables pour réduire l'impact environnemental."
  }
];

const Features: React.FC = () => {
  return (
    <section className="py-16 bg-neutral-100">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12 animate-slide-up">
          <h2 className="text-3xl font-bold mb-4">Pourquoi choisir Axes Trade ?</h2>
          <p className="text-lg text-neutral-800 max-w-3xl mx-auto">
            Nous offrons des solutions complètes pour répondre à tous vos besoins d'impression professionnelle.
          </p>
        </div>
        
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
          {features.map((feature, index) => (
            <div key={index} className="bg-white p-6 rounded-lg shadow-md hover-scale">
              <div className="w-16 h-16 bg-primary-light rounded-full flex items-center justify-center mb-4 mx-auto">
                <i className={`fas fa-${feature.icon} text-white text-2xl`}></i>
              </div>
              <h3 className="text-xl font-semibold text-center mb-3">{feature.title}</h3>
              <p className="text-center text-neutral-800">
                {feature.description}
              </p>
            </div>
          ))}
        </div>
      </div>
    </section>
  );
};

export default Features;
