// vue-axes-trade/src/components/Footer.vue
<script setup lang="ts">
import { library } from '@fortawesome/fontawesome-svg-core'
import { faFacebook, faTwitter, faLinkedin, faInstagram } from '@fortawesome/free-brands-svg-icons'
import { FontAwesomeIcon } from '@fortawesome/vue-fontawesome'

// Ajouter les icônes à la bibliothèque
library.add(faFacebook, faTwitter, faLinkedin, faInstagram)

// Année courante pour le copyright
const currentYear = new Date().getFullYear()
</script>

<template>
  <footer class="bg-gray-800 text-white pt-12 pb-6">
    <div class="container mx-auto px-4">
      <div class="grid grid-cols-1 md:grid-cols-4 gap-8">
        <!-- Logo et description -->
        <div class="md:col-span-1">
          <div class="brand-name text-xl font-bold mb-4">
            <span class="axes">Axes</span><span class="trade">Trade</span>
          </div>
          <p class="text-gray-300 mb-4">
            Spécialiste en solutions d'impression professionnelles et matériel bureautique de qualité.
          </p>
          <div class="flex space-x-4">
            <a href="#" class="text-gray-300 hover:text-white">
              <FontAwesomeIcon :icon="['fab', 'facebook']" class="text-xl" />
            </a>
            <a href="#" class="text-gray-300 hover:text-white">
              <FontAwesomeIcon :icon="['fab', 'twitter']" class="text-xl" />
            </a>
            <a href="#" class="text-gray-300 hover:text-white">
              <FontAwesomeIcon :icon="['fab', 'linkedin']" class="text-xl" />
            </a>
            <a href="#" class="text-gray-300 hover:text-white">
              <FontAwesomeIcon :icon="['fab', 'instagram']" class="text-xl" />
            </a>
          </div>
        </div>

        <!-- Liens rapides -->
        <div class="md:col-span-1">
          <h3 class="text-lg font-bold mb-4 text-white">Liens rapides</h3>
          <ul class="space-y-2">
            <li><router-link to="/" class="text-gray-300 hover:text-white">Accueil</router-link></li>
            <li><router-link to="/products" class="text-gray-300 hover:text-white">Produits</router-link></li>
            <li><router-link to="/blog" class="text-gray-300 hover:text-white">Blog</router-link></li>
            <li><router-link to="/#contact" class="text-gray-300 hover:text-white">Contact</router-link></li>
          </ul>
        </div>

        <!-- Produits -->
        <div class="md:col-span-1">
          <h3 class="text-lg font-bold mb-4 text-white">Produits</h3>
          <ul class="space-y-2">
            <li><router-link to="/products?category=printers" class="text-gray-300 hover:text-white">Imprimantes</router-link></li>
            <li><router-link to="/products?category=scanners" class="text-gray-300 hover:text-white">Scanners</router-link></li>
            <li><router-link to="/products?category=mfp" class="text-gray-300 hover:text-white">Multifonctions</router-link></li>
            <li><router-link to="/products?category=accessories" class="text-gray-300 hover:text-white">Accessoires</router-link></li>
          </ul>
        </div>

        <!-- Contact -->
        <div class="md:col-span-1">
          <h3 class="text-lg font-bold mb-4 text-white">Contact</h3>
          <address class="not-italic text-gray-300">
            <p class="mb-2">123 Avenue des Imprimantes</p>
            <p class="mb-2">75000 Paris, France</p>
            <p class="mb-2">Téléphone: +33 1 23 45 67 89</p>
            <p class="mb-2">Email: contact@axestrade.com</p>
          </address>
        </div>
      </div>

      <!-- Copyright -->
      <div class="border-t border-gray-700 mt-8 pt-6 text-center text-gray-400">
        <p>&copy; {{ currentYear }} AxesTrade. Tous droits réservés.</p>
      </div>
    </div>
  </footer>
</template>

// client/src/components/Footer.tsx
import React from "react";
import { scrollToSection } from "@/lib/utils";

const quickLinks = [
  { id: "hero", label: "Accueil" },
  { id: "products", label: "Produits" },
  { id: "services", label: "Services" },
  { id: "about", label: "À Propos" },
  { id: "contact", label: "Contact" },
  { id: "#", label: "Blog" }
];

const products = [
  { id: "#", label: "Imprimantes laser" },
  { id: "#", label: "Imprimantes jet d'encre" },
  { id: "#", label: "Multifonctions" },
  { id: "#", label: "Scanners" },
  { id: "#", label: "Consommables" },
  { id: "#", label: "Accessoires" }
];

const Footer: React.FC = () => {
  const handleLinkClick = (id: string) => {
    if (id !== "#") {
      scrollToSection(id);
    }
  };

  return (
    <footer className="bg-neutral-900 text-white pt-16 pb-8">
      <div className="container mx-auto px-4">
        <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8 mb-12">
          {/* Company Info */}
          <div>
            <div className="text-2xl font-bold mb-6">
              <span className="text-secondary">AXES</span> TRADE
            </div>
            <p className="mb-6 text-neutral-400">
              Votre partenaire de confiance pour toutes vos solutions d'impression professionnelles depuis 2010.
            </p>
            <div className="flex space-x-4">
              <a href="#" className="text-neutral-400 hover:text-secondary transition-colors" aria-label="Facebook">
                <i className="fab fa-facebook-f"></i>
              </a>
              <a href="#" className="text-neutral-400 hover:text-secondary transition-colors" aria-label="LinkedIn">
                <i className="fab fa-linkedin-in"></i>
              </a>
              <a href="#" className="text-neutral-400 hover:text-secondary transition-colors" aria-label="Twitter">
                <i className="fab fa-twitter"></i>
              </a>
              <a href="#" className="text-neutral-400 hover:text-secondary transition-colors" aria-label="Instagram">
                <i className="fab fa-instagram"></i>
              </a>
            </div>
          </div>
          
          {/* Quick Links */}
          <div>
            <h3 className="text-lg font-semibold mb-6">Liens rapides</h3>
            <ul className="space-y-3">
              {quickLinks.map((link, index) => (
                <li key={index}>
                  <button
                    onClick={() => handleLinkClick(link.id)}
                    className="text-neutral-400 hover:text-secondary transition-colors"
                  >
                    {link.label}
                  </button>
                </li>
              ))}
            </ul>
          </div>
          
          {/* Products */}
          <div>
            <h3 className="text-lg font-semibold mb-6">Nos produits</h3>
            <ul className="space-y-3">
              {products.map((product, index) => (
                <li key={index}>
                  <a href={product.id} className="text-neutral-400 hover:text-secondary transition-colors">
                    {product.label}
                  </a>
                </li>
              ))}
            </ul>
          </div>
          
          {/* Contact */}
          <div>
            <h3 className="text-lg font-semibold mb-6">Contact</h3>
            <ul className="space-y-3 text-neutral-400">
              <li className="flex items-start">
                <i className="fas fa-map-marker-alt mt-1 mr-3 text-secondary"></i>
                <span>123 Avenue des Imprimeurs<br/>75001 Paris, France</span>
              </li>
              <li className="flex items-center">
                <i className="fas fa-phone-alt mr-3 text-secondary"></i>
                <a href="tel:+33123456789" className="hover:text-secondary transition-colors">01 23 45 67 89</a>
              </li>
              <li className="flex items-center">
                <i className="fas fa-envelope mr-3 text-secondary"></i>
                <a href="mailto:contact@axestrade.com" className="hover:text-secondary transition-colors">contact@axestrade.com</a>
              </li>
            </ul>
          </div>
        </div>
        
        <hr className="border-neutral-800 mb-8" />
        
        <div className="flex flex-col md:flex-row justify-between items-center text-neutral-500 text-sm">
          <div className="mb-4 md:mb-0">
            &copy; {new Date().getFullYear()} Axes Trade. Tous droits réservés.
          </div>
          <div className="flex space-x-4">
            <a href="#" className="hover:text-secondary transition-colors">Mentions légales</a>
            <a href="#" className="hover:text-secondary transition-colors">Politique de confidentialité</a>
            <a href="#" className="hover:text-secondary transition-colors">CGV</a>
          </div>
        </div>
      </div>
    </footer>
  );
};

export default Footer;
