// vue-axes-trade/src/components/Testimonials.vue
<script setup lang="ts">
// Testimonials.vue
import { ref } from 'vue'

// Define testimonial data type
type Testimonial = {
  id: number;
  text: string;
  author: string;
  position: string;
  rating: number;
};

// Sample testimonials data
const testimonials = ref<Testimonial[]>([
  {
    id: 1,
    text: "Axes Trade a transformé notre système d'impression professionnel. Leur service client est exceptionnel et les imprimantes achetées sont d'une fiabilité remarquable.",
    author: "Marie Dupont",
    position: "Directrice des opérations, Design Studio",
    rating: 5
  },
  {
    id: 2,
    text: "En tant que bureau d'architecture, nous avions besoin d'imprimantes grand format très précises. Axes Trade nous a fourni exactement ce qu'il nous fallait avec un support technique continu.",
    author: "Jean Martin",
    position: "Architecte principal, ArchiFuture",
    rating: 5
  },
  {
    id: 3,
    text: "Nous utilisons les solutions d'impression d'Axes Trade depuis plus de 3 ans maintenant. Leur équipe est réactive et leurs produits sont parfaitement adaptés à nos besoins.",
    author: "Sophie Leblanc",
    position: "Responsable IT, Entreprise Média",
    rating: 4
  }
]);

// Generate star rating display
const getRatingStars = (rating: number) => {
  return Array(5)
    .fill(0)
    .map((_, i) => i < rating);
};
</script>

<template>
  <section id="testimonials" class="py-16 bg-gray-50">
    <div class="container mx-auto px-4">
      <div class="text-center mb-12">
        <h2 class="text-3xl font-bold mb-4">Ce que nos clients disent</h2>
        <p class="text-xl text-gray-600 max-w-3xl mx-auto">
          Découvrez pourquoi les entreprises de toutes tailles font confiance à Axes Trade pour leurs solutions d'impression.
        </p>
      </div>
      
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
        <div v-for="testimonial in testimonials" :key="testimonial.id" 
             class="bg-white p-6 rounded-lg shadow-md hover:shadow-lg transition-shadow duration-300">
          <div class="flex mb-4">
            <div v-for="(isFilled, index) in getRatingStars(testimonial.rating)" :key="index">
              <font-awesome-icon 
                :icon="['fas', 'star']" 
                class="text-yellow-400 mr-1" 
                v-if="isFilled" 
              />
              <font-awesome-icon 
                :icon="['fas', 'star']" 
                class="text-gray-300 mr-1" 
                v-else 
              />
            </div>
          </div>
          
          <p class="text-gray-700 italic mb-4">"{{ testimonial.text }}"</p>
          
          <div class="mt-auto">
            <p class="font-bold">{{ testimonial.author }}</p>
            <p class="text-gray-600 text-sm">{{ testimonial.position }}</p>
          </div>
        </div>
      </div>
      
      <div class="text-center mt-12">
        <button class="inline-block bg-blue-600 hover:bg-blue-700 text-white font-semibold py-3 px-6 rounded-lg transition duration-300 transform hover:scale-105">
          Voir tous les témoignages
        </button>
      </div>
    </div>
  </section>
</template>

<style scoped>
/* Additional styling can be added here if needed */
</style>

// client/src/components/Testimonials.tsx
import React, { useState, useRef } from "react";

type Testimonial = {
  id: number;
  text: string;
  author: string;
  position: string;
  rating: number;
};

const testimonials: Testimonial[] = [
  {
    id: 1,
    text: "Axes Trade nous a fourni une solution d'impression complète qui nous a permis de réduire nos coûts de 30%. Le service client est exceptionnel et réactif.",
    author: "Sophie Martin",
    position: "Directrice Administrative, Groupe Dufour",
    rating: 5
  },
  {
    id: 2,
    text: "Nous travaillons avec Axes Trade depuis plus de 5 ans. Leur équipe technique est toujours disponible et intervient rapidement en cas de besoin. Je les recommande vivement.",
    author: "Thomas Dubois",
    position: "Responsable IT, Cabinet Juridique Lambert",
    rating: 5
  },
  {
    id: 3,
    text: "Axes Trade nous a aidés à mettre en place une solution d'impression éco-responsable. Leurs conseils nous ont permis d'optimiser notre consommation tout en améliorant la qualité.",
    author: "Marie Leclerc",
    position: "Gérante, Imprimerie Eco-Print",
    rating: 4.5
  }
];

const Testimonials: React.FC = () => {
  const [activeSlide, setActiveSlide] = useState(0);
  const carouselRef = useRef<HTMLDivElement>(null);

  const scrollToSlide = (index: number) => {
    setActiveSlide(index);
    if (carouselRef.current) {
      const slideWidth = carouselRef.current.querySelector('div')?.offsetWidth || 0;
      carouselRef.current.scrollTo({
        left: slideWidth * index,
        behavior: 'smooth'
      });
    }
  };

  const renderStars = (rating: number) => {
    const stars = [];
    const fullStars = Math.floor(rating);
    const hasHalfStar = rating % 1 !== 0;

    for (let i = 0; i < fullStars; i++) {
      stars.push(<i key={`full-${i}`} className="fas fa-star"></i>);
    }

    if (hasHalfStar) {
      stars.push(<i key="half" className="fas fa-star-half-alt"></i>);
    }

    const emptyStars = 5 - stars.length;
    for (let i = 0; i < emptyStars; i++) {
      stars.push(<i key={`empty-${i}`} className="far fa-star"></i>);
    }

    return stars;
  };

  return (
    <section className="py-16 bg-primary text-white">
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="text-3xl font-bold mb-4">Ce que nos clients disent</h2>
          <p className="text-lg max-w-3xl mx-auto opacity-90">
            Découvrez les témoignages de nos clients satisfaits par nos services et solutions.
          </p>
        </div>

        <div className="relative">
          <div 
            ref={carouselRef} 
            className="testimonial-carousel flex overflow-x-auto pb-8 -mx-4 px-4 gap-4 scrollbar-hide"
          >
            {testimonials.map((testimonial) => (
              <div 
                key={testimonial.id} 
                className="min-w-[300px] w-full md:w-1/2 lg:w-1/3 flex-shrink-0 p-6 bg-white rounded-lg shadow-md text-neutral-800"
              >
                <div className="flex items-center mb-4">
                  <div className="text-yellow-400 flex">
                    {renderStars(testimonial.rating)}
                  </div>
                </div>
                <p className="italic mb-6">
                  "{testimonial.text}"
                </p>
                <div className="flex items-center">
                  <div className="w-12 h-12 bg-neutral-300 rounded-full mr-4 flex items-center justify-center">
                    <i className="fas fa-user text-neutral-600"></i>
                  </div>
                  <div>
                    <h4 className="font-semibold">{testimonial.author}</h4>
                    <p className="text-sm text-neutral-600">{testimonial.position}</p>
                  </div>
                </div>
              </div>
            ))}
          </div>
          
          <div className="flex justify-center space-x-2 mt-6">
            {testimonials.map((_, index) => (
              <button 
                key={index}
                className={`w-3 h-3 rounded-full bg-white ${activeSlide === index ? 'opacity-100' : 'opacity-50'}`}
                onClick={() => scrollToSlide(index)}
                aria-label={`Go to slide ${index + 1}`}
              ></button>
            ))}
          </div>
        </div>
      </div>
    </section>
  );
};

export default Testimonials;
