// client/src/components/Hero.tsx
import React from "react";
import { Button } from "@/components/ui/button";
import { scrollToSection } from "@/lib/utils";

const Hero: React.FC = () => {
  return (
    <section id="hero" className="relative pt-24 md:pt-0">
      <div className="relative h-[70vh] min-h-[500px] bg-neutral-800 overflow-hidden">
        <div className="absolute inset-0 bg-gradient-overlay"></div>
        <img 
          src="https://images.unsplash.com/photo-1588681664899-f142ff2dc9b1?ixlib=rb-1.2.1&auto=format&fit=crop&w=1920&q=80" 
          alt="Environnement de bureau professionnel avec imprimantes" 
          className="absolute inset-0 w-full h-full object-cover"
        />
        <div className="container mx-auto px-4 h-full flex items-center relative z-10">
          <div className="max-w-2xl animate-fade-in">
            <h1 className="text-4xl md:text-5xl font-bold text-white leading-tight mb-4">
              Solutions d'impression professionnelles pour votre entreprise
            </h1>
            <p className="text-lg md:text-xl text-white opacity-90 mb-8">
              Axes Trade vous accompagne dans le choix et la gestion de vos équipements d'impression. Expertise, conseil et service de qualité.
            </p>
            <div className="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
              <Button 
                onClick={() => scrollToSection("products")} 
                className="bg-secondary hover:bg-secondary-dark text-white font-semibold px-6 py-3 h-auto"
              >
                Découvrir nos produits
              </Button>
              <Button 
                onClick={() => scrollToSection("contact")} 
                variant="outline"
                className="bg-white hover:bg-neutral-100 text-primary font-semibold px-6 py-3 h-auto"
              >
                Nous contacter
              </Button>
            </div>
          </div>
        </div>
      </div>

      {/* Quick Contact Bar */}
      <div className="bg-primary py-3 text-white">
        <div className="container mx-auto px-4 flex flex-wrap justify-between items-center">
          <div className="flex items-center space-x-6 my-2">
            <a href="tel:+33123456789" className="flex items-center hover:text-secondary transition-colors">
              <i className="fas fa-phone-alt mr-2"></i>
              <span>01 23 45 67 89</span>
            </a>
            <a href="mailto:contact@axestrade.com" className="flex items-center hover:text-secondary transition-colors">
              <i className="fas fa-envelope mr-2"></i>
              <span>contact@axestrade.com</span>
            </a>
          </div>
          <div className="flex items-center space-x-4 my-2">
            <a href="#" className="hover:text-secondary transition-colors" aria-label="Facebook">
              <i className="fab fa-facebook-f"></i>
            </a>
            <a href="#" className="hover:text-secondary transition-colors" aria-label="LinkedIn">
              <i className="fab fa-linkedin-in"></i>
            </a>
            <a href="https://wa.me/33123456789" className="hover:text-secondary transition-colors" aria-label="WhatsApp">
              <i className="fab fa-whatsapp"></i>
            </a>
          </div>
        </div>
      </div>
    </section>
  );
};

export default Hero;

// vue-axes-trade/src/components/Hero.vue
<script setup lang="ts">
// Aucune logique spécifique n'est nécessaire pour le composant Hero
</script>

<template>
  <section class="py-16 md:py-20 lg:py-24 bg-gradient-to-r from-gray-50 to-gray-100">
    <div class="container mx-auto px-4">
      <div class="flex flex-col lg:flex-row items-center">
        <div class="lg:w-1/2 lg:pr-12 mb-10 lg:mb-0">
          <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold mb-6">
            Solutions d'impression professionnelles
          </h1>
          <p class="text-lg md:text-xl text-gray-600 mb-8 max-w-2xl">
            <span class="brand-name"><span class="text-axes font-bold">Axes</span><span class="text-trade font-bold">Trade</span></span> vous propose une gamme complète d'imprimantes et de solutions d'impression pour répondre à tous vos besoins professionnels.
          </p>
          <div class="flex flex-col sm:flex-row space-y-4 sm:space-y-0 sm:space-x-4">
            <router-link to="/products" class="btn btn-primary">
              Découvrir nos produits
            </router-link>
            <router-link to="/#contact" class="btn btn-outline">
              Nous contacter
            </router-link>
          </div>
        </div>
        <div class="lg:w-1/2">
          <div class="relative">
            <!-- Placeholder pour image d'imprimante -->
            <div class="bg-gray-200 rounded-lg aspect-video flex items-center justify-center">
              <div class="text-gray-500 text-xl">Image d'imprimante professionnelle</div>
            </div>
            <!-- Badges flottants -->
            <div class="absolute -top-4 -right-4 bg-secondary text-white px-4 py-2 rounded-full font-bold">
              Nouveauté
            </div>
            <div class="absolute bottom-4 -left-4 bg-primary text-white p-3 rounded-lg shadow-lg">
              <div class="text-sm">Garantie</div>
              <div class="text-xl font-bold">3 ans</div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>
